post_grade_declaration

CREATE TABLE `test` (
  `id` varchar(25) DEFAULT NULL COMMENT '主键',
  `name` varchar(25) DEFAULT NULL COMMENT '姓名'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='wrwer'

CREATE TABLE GDJ_SBSQB (
	GDJ_SBSQB__ZZJG varchar (10) COLLATE Chinese_PRC_CI_AS NOT NULL ,
	GDJ_SBSQB__SBBJ varchar (11) COLLATE Chinese_PRC_CI_AS NOT NULL ,
	GDJ_SBSQB__YSB bit NULL ,
	GDJ_SBSQB__SBSJ datetime NULL ,
	GDJ_SBSQB__ZGTG bit NULL ,
	GDJ_SBSQB__ZGBM datetime NULL ,
	GDJ_SBSQB__ZGBM1 text COLLATE Chinese_PRC_CI_AS NULL ,
	GDJ_SBSQB__RSTG bit NULL ,
	GDJ_SBSQB__RSBM datetime NULL ,
	GDJ_SBSQB__RSBM1 text COLLATE Chinese_PRC_CI_AS NULL ,
	GDJ_SBSQB__RSTTG bit NULL ,
	GDJ_SBSQB__RSTRQ datetime NULL ,
	GDJ_SBSQB__RSTYJ text COLLATE Chinese_PRC_CI_AS NULL ,
	GDJ_SBSQB__BZ text COLLATE Chinese_PRC_CI_AS NULL ,
	GDJ_SBSQB__WJID int NULL ,
	GDJ_SBSQB__XTG bit NULL ,
	GDJ_SBSQB__XRQ datetime NULL ,
	GDJ_SBSQB__XYJ text COLLATE Chinese_PRC_CI_AS NULL ,
	GDJ_SBSQB__GWFA text COLLATE Chinese_PRC_CI_AS NULL ,
	GDJ_SBSQB__SLYJ text COLLATE Chinese_PRC_CI_AS NULL ,
	GDJ_SBSQB__SLYJ2 text COLLATE Chinese_PRC_CI_AS NULL ,
	GDJ_SBSQB__SJTGWS int NULL 
) ON PRIMARY TEXTIMAGE_ON PRIMARY
;
CREATE TABLE GDJ_SBXQ (
	GDJ_SBXQ__ZZJG varchar (10) COLLATE Chinese_PRC_CI_AS NOT NULL ,
	GDJ_SBXQ__SBBJ varchar (11) COLLATE Chinese_PRC_CI_AS NOT NULL ,
	GDJ_SBXQ__DJ varchar (3) COLLATE Chinese_PRC_CI_AS NOT NULL ,
	GDJ_SBXQ__SL int NULL ,
	GDJ_SBXQ__HZSL int NULL ,
	GDJ_SBXQ__BZ text COLLATE Chinese_PRC_CI_AS NULL 
) ON PRIMARY TEXTIMAGE_ON PRIMARY
;

CREATE TABLE GDJ_XZXQ (
	GDJ_XZXQ__ZZJG varchar (10) COLLATE Chinese_PRC_CI_AS NOT NULL ,
	GDJ_XZXQ__DJ varchar (3) COLLATE Chinese_PRC_CI_AS NOT NULL ,
	GDJ_XZXQ__SL int NULL ,
	GDJ_XZXQ__BZ text COLLATE Chinese_PRC_CI_AS NULL 
) ON PRIMARY TEXTIMAGE_ON PRIMARY
;


